version: '3.8'
services:
  db:
    image: mongo:latest
    restart: always

    ports:
      - 27017:27017
    volumes:
      - data:/var/lib/mongodb/data
  
  app:
    build: .
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - db
volumes:
  data: